# 정확도(Accuracy)
## titanic 엉터리 분류기

In [13]:
import numpy as np
from sklearn.base import BaseEstimator

In [14]:
class MyDummyClassifier(BaseEstimator):
    # fit(),predict() method만 제정의(overriding)
    def fit(self , X , y=None):
        pass
    def predict(self, X):
        pred = np.zeros((X.shape[0], 1))
        for i in range (X.shape[0]):
            if X['Sex'].iloc[i] == 1: # 여성인 경우
                pred[i] = 0
            else:
                pred[i] = 1

        return pred

In [15]:
X = np.ones((10,5))
X.shape[0]

10

In [32]:
import pandas as pd
titanic_df = pd.read_csv("../01.introduction/input/train.csv")

In [39]:
from sklearn.model_selection import train_test_split
y_titanic_df = titanic_df['Survived']
X_titanic_df= titanic_df.drop('Survived', axis=1)
X_train, X_test, y_train, y_test=train_test_split(
    X_titanic_df, y_titanic_df,test_size=0.2, random_state=11
    )

In [77]:
my_clf = MyDummyClassifier()
my_clf.fit(X_train, y_train)
my_pre = my_clf.predict(X_test)

In [41]:

from sklearn.metrics import accuracy_score
print('Dummy Classifier의 정확도: {0:.4f}'.format(accuracy_score(y_test,
 mypredictions)))

Dummy Classifier의 정확도: 0.3408


# 손글씨

In [64]:
class MyFakeClassifier(BaseEstimator):
    # fit(),predict() method만 제정의(overriding)
    def fit(self , X , y):
        pass
    def predict(self, X):
        pred = np.zeros((len(X), 1), dtype=bool)
        return pred

In [65]:
from sklearn.datasets import load_digits
digits = load_digits()
y = (digits.target==7).astype(int)
X_train, X_test, y_train, y_test=train_test_split(
    digits.data,y,random_state = 11
)

In [66]:
print('레이블 테스트 세트 크기 :',y_test.shape)
print('테스트 세트 레이블 0과 1의 분포도')
print(pd.Series(y_test).value_counts())

레이블 테스트 세트 크기 : (450,)
테스트 세트 레이블 0과 1의 분포도
0    405
1     45
dtype: int64


In [67]:
fakecf = MyFakeClassifier()
fakecf.fit(X_train,y_train)
fakepred = fakecf.predict(X_test)
score = accuracy_score(y_test,fakepred)
print(f'모든 예측을 0으로 하여도 정확도는 : {score:3f}')

모든 예측을 0으로 하여도 정확도는 : 0.900000


# 오차행렬
## 

In [70]:
from sklearn.metrics import precision_score,recall_score,confusion_matrix

def get_clf_eval(y_test, pred):
    confusion = confusion_matrix(y_test,pred)
    accuracy = accuracy_score(y_test,pred)
    precision = precision_score(y_test,pred)
    recall = recall_score(y_test, pred)
    print('오차행렬')
    print(confusion)
    print(f'정확도 : {accuracy:4f} 정밀도:{precision:4f}, 재현율:{recall:4f}')

In [79]:
import pandas as pd
titanic_df = pd.read_csv("../01.introduction/input/train.csv")

In [80]:
titanic_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [88]:
from sklearn.model_selection import train_test_split
y_titanic_df = titanic_df['Survived']
X_titanic_df= titanic_df.drop('Survived', axis=1)
X_train, X_test, y_train, y_test=train_test_split(
    X_titanic_df, y_titanic_df,test_size=0.2, random_state=11
    )

In [87]:
from sklearn.linear_model import LogisticRegression

lr_clf = LogisticRegression()
lr_clf.fit(X_train,y_train)
pred = lr_clf.predict(X_test)
get_clf_eval(y_test,pred)

ValueError: could not convert string to float: 'STON/O 2. 3101293'

In [89]:
from sklearn.preprocessing import Binarizer

X = [[1,-1,2],
    [2,0,0],
    [0,1.1,1.2]]

binarizer = Binarizer(threshold=1.1)
print(binarizer.fit_transform(X))

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [90]:
binarizer = Binarizer(threshold=1)
print(binarizer.fit_transform(X))

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 1.]]
