## 다중회귀
- iris에서 class,sl,sw,pw ==> petal length구하기
### pl = [w1,w2,w3,w4][C,sl,sw,pl].T + bias
### test size = 0.2
### sl=?,sw=?,pw=?  

In [353]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.datasets import load_iris
iris = load_iris()

In [354]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [355]:
df = pd.DataFrame(data=iris.data,columns=["SL","SW","PL","PW"])
# df['C'] = iris.target_names[iris.target]
#df.C => 0 = setosa, 1 = versicolor, 2 = virginica
df['C'] = iris.target
df

SL   SW   PL   PW  C
0    5.1  3.5  1.4  0.2  0
1    4.9  3.0  1.4  0.2  0
2    4.7  3.2  1.3  0.2  0
3    4.6  3.1  1.5  0.2  0
4    5.0  3.6  1.4  0.2  0
..   ...  ...  ...  ... ..
145  6.7  3.0  5.2  2.3  2
146  6.3  2.5  5.0  1.9  2
147  6.5  3.0  5.2  2.0  2
148  6.2  3.4  5.4  2.3  2
149  5.9  3.0  5.1  1.8  2

[150 rows x 5 columns]

## PL

In [356]:
y = df["PL"] 
X = df[["SL","SW","PW","C"]] 
X_train, X_test, y_tarin, y_test = train_test_split(X, y, test_size = 0.2,random_state=2021) 

lr = LinearRegression()
lr.fit(X_train,y_tarin)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [357]:
pred = lr.predict(X_test)
mse = mean_squared_error(y_test,pred)
r2 = r2_score(y_test,pred)
print(f'mse : ,{mse:.2f}, RMSE : {np.sqrt(mse):.2f}')
print(f'R_squared : {r2:.4f}')

mse : ,0.10, RMSE : 0.31
R_squared : 0.9682


In [358]:
lr.coef_

array([ 0.68227323, -0.51925158,  1.11668415,  0.37500635])

In [359]:
lr.intercept_

-0.36699949396033205

- 회기식
#### 0.737*SL-0.598*SW+1.08*PW+0.353*C-0.36


In [360]:
(lr.coef_* X).sum(axis=1) + lr.intercept_

0      1.518550
1      1.641721
2      1.401416
3      1.385114
4      1.398398
         ...   
145    5.964863
146    5.504906
147    5.493403
148    5.416025
149    4.860702
Length: 150, dtype: float64

교차검증

In [334]:
neg_mean_scores = cross_val_score(lr, X, y,
                                scoring='neg_mean_squared_error', cv=5)
rmse_scores = np.sqrt(-neg_mean_scores)
avg_rmse = np.average(rmse_scores)

print('개별 MSE: ',np.round(neg_mean_scores,2))
print('개별 RMSE: ',np.round(rmse_scores,2))
print(f'평균 RMSE: {avg_rmse:.4f}')

개별 MSE:  [-0.06 -0.08 -0.14 -0.1  -0.21]
개별 RMSE:  [0.25 0.28 0.38 0.32 0.46]
평균 RMSE: 0.3387


## SL

In [335]:
y = df["SL"] 
X = df[["PL","SW","PW","C"]] 

X_train, X_test, y_tarin, y_test = train_test_split(X, y, test_size = 0.2,random_state=2021) 

lr = LinearRegression()
lr.fit(X_train,y_tarin)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [336]:
pred = lr.predict(X_test)
mse = mean_squared_error(y_test,pred)
r2 = r2_score(y_test,pred)
print(f'mse : ,{mse:.2f}, RMSE : {np.sqrt(mse):.2f}')
print(f'R_squared : {r2:.4f}')

mse : ,0.10, RMSE : 0.32
R_squared : 0.8181


In [337]:
lr.coef_

array([ 0.74311359,  0.62338382, -0.4560811 , -0.17450858])

In [338]:
lr.intercept_

1.8524911037970018

- 회기식
#### 0.744*pl+0.5*SW-0.426*PW-0.215*C-1.93

In [339]:
(lr.coef_* X).sum(axis=1) + lr.intercept_

0      4.983477
1      4.671785
2      4.722151
3      4.808435
4      5.045816
         ...   
145    6.188830
146    5.910947
147    6.325654
148    6.586806
149    6.342559
Length: 150, dtype: float64

교차검증

In [340]:
neg_mean_scores = cross_val_score(lr, X, y,
                                scoring='neg_mean_squared_error', cv=5)
rmse_scores = np.sqrt(-neg_mean_scores)
avg_rmse = np.average(rmse_scores)

print('개별 MSE: ',np.round(neg_mean_scores,2))
print('개별 RMSE: ',np.round(rmse_scores,2))
print(f'평균 RMSE: {avg_rmse:.4f}')

개별 MSE:  [-0.06 -0.08 -0.14 -0.1  -0.14]
개별 RMSE:  [0.25 0.29 0.37 0.31 0.38]
평균 RMSE: 0.3199


## SW

In [341]:
y = df["SW"] 
X = df[["PL","SL","PW","C"]] 

X_train, X_test, y_tarin, y_test = train_test_split(X, y, test_size = 0.2,random_state=2021) 

lr = LinearRegression()
lr.fit(X_train,y_tarin)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [342]:
pred = lr.predict(X_test)
mse = mean_squared_error(y_test,pred)
r2 = r2_score(y_test,pred)
print(f'mse : ,{mse:.2f}, RMSE : {np.sqrt(mse):.2f}')
print(f'R_squared : {r2:.4f}')

mse : ,0.10, RMSE : 0.31
R_squared : 0.4639


In [343]:
lr.coef_

array([-0.54159643,  0.6062082 ,  0.68893796, -0.22240148])

In [344]:
lr.intercept_

0.9363345581710063

- 회기식
#### -0.546*PL+0.606*SL+0.689*PW-0.222*C+0.936

In [345]:
(lr.coef_* X).sum(axis=1) + lr.intercept_

0      3.407549
1      3.286307
2      3.219225
3      3.050285
4      3.346928
         ...   
145    3.321382
146    2.911643
147    2.993459
148    2.909959
149    2.546107
Length: 150, dtype: float64

교차검증

In [346]:
neg_mean_scores = cross_val_score(lr, X, y,
                                scoring='neg_mean_squared_error', cv=5)
rmse_scores = np.sqrt(-neg_mean_scores)
avg_rmse = np.average(rmse_scores)

print('개별 MSE: ',np.round(neg_mean_scores,2))
print('개별 RMSE: ',np.round(rmse_scores,2))
print(f'평균 RMSE: {avg_rmse:.4f}')

개별 MSE:  [-0.08 -0.11 -0.16 -0.08 -0.11]
개별 RMSE:  [0.28 0.33 0.41 0.29 0.33]
평균 RMSE: 0.3289


## PW

In [347]:
y = df["SW"] # 종속변수 설정
X = df[["PL","SL","PW","C"]] 

X_train, X_test, y_tarin, y_test = train_test_split(X, y, test_size = 0.2,random_state=2021) 

lr = LinearRegression()
lr.fit(X_train,y_tarin)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [348]:
pred = lr.predict(X_test)
mse = mean_squared_error(y_test,pred)
r2 = r2_score(y_test,pred)
print(f'mse : ,{mse:.2f}, RMSE : {np.sqrt(mse):.2f}')
print(f'R_squared : {r2:.4f}')

mse : ,0.08, RMSE : 0.28
R_squared : 0.4935


In [349]:
lr.coef_

array([-0.64724017,  0.60817935,  0.65116816,  0.04421472])

In [350]:
lr.intercept_

1.1042041701845056

- 회기식
#### -0.647*PL+0.608*SL+0.651*PW-0.044*C+1.104

In [351]:
(lr.coef_* X).sum(axis=1) + lr.intercept_

0      3.430016
1      3.308380
2      3.251469
3      3.061203
4      3.369198
         ...   
145    3.399473
146    3.025182
147    3.082487
148    2.965935
149    2.652070
Length: 150, dtype: float64

In [352]:
neg_mean_scores = cross_val_score(lr, X, y,
                                scoring='neg_mean_squared_error', cv=5)
rmse_scores = np.sqrt(-neg_mean_scores)
avg_rmse = np.average(rmse_scores)

print('개별 MSE: ',np.round(neg_mean_scores,2))
print('개별 RMSE: ',np.round(rmse_scores,2))
print(f'평균 RMSE: {avg_rmse:.4f}')

개별 MSE:  [-0.08 -0.11 -0.16 -0.08 -0.11]
개별 RMSE:  [0.28 0.33 0.41 0.29 0.33]
평균 RMSE: 0.3289
